Repository Ericsson/CodecheckerVSCodePlugin, pull requests merged in 2022-01, with the labels that each got.

#42 Publish package to OpenVSX
  .github/workflows/deploy.yml
Labels: package

#44 Fix hidden Previous step button in CodeLens
  src/editor/codelens.ts
Labels: bugfix

#43 Add screenshots to readme
  README.md
  media/codechecker-analysis.gif
  media/codechecker-repr-step.gif
  media/codechecker-splash.png
  media/codechecker-tasks.gif
Labels: documentation, enhancement

#45 Support new CodeChecker analyzer-version format
  src/backend/executor/bridge.ts
Labels: enhancement

#46 Change minimum supported CodeChecker version to 6.18.2
  README.md
  src/backend/executor/bridge.ts
Labels: enhancement

#48 Use matrix strategy at deploy github action
  .github/workflows/deploy.yml
  README.md
Labels: refactoring

#52 Find compilation database automatically in the project
  src/backend/executor/bridge.ts
Labels: bugfix

#53 Remove `fast-plist` dependency
  package.json
  yarn.lock
Labels: refactoring

#55 Set priority order for settings items
  package.json
Labels: refactoring

#54 Wait for terminal initialization for CodeChecker log command
  src/editor/initialize.ts
Labels: bugfix

#60 Keep active repr. steps open when switching files
  src/sidebar/views/reports.ts
Labels: enhancement

#63 Fix adding selectedEntry to openedFiles
  src/backend/processor/diagnostics.ts
Labels: bugfix

#58 Reduce number of `parse` calls
  src/backend/processor/diagnostics.ts
Labels: bugfix

#64 Remove unclosable CodeChecker analysis in progress window
  src/backend/executor/process.ts
  src/editor/executor.ts
  src/sidebar/views/overview.ts
Labels: enhancement

#65 Bump up version to 1.1.0
  package.json
Labels: package

#66 Bump up version to 1.1.1
  package.json
Labels: package

#67 Add icons to the statusbar text
  src/editor/executor.ts
Labels: enhancement
