Repository Ericsson/CodecheckerVSCodePlugin, pull requests merged in 2022-02, with the labels that each got.

#68 Show checker name in the bug tree for each report
  src/sidebar/views/reports.ts
Labels: enhancement

#69 Check supported CodeChecker version on configuration change
  src/backend/executor/bridge.ts
Labels: enhancement

#70 Fix showing diagnostics in the Problems pane
  src/editor/diagnostics.ts
Labels: bugfix

#85 Bump up version to 1.2.0
  package.json
Labels: package

#75 Fix keyboard navigation commands
  src/editor/navigation.ts
Labels: bugfix

#91 Change CodeChecker analysis output to .codechecker/reports
  src/backend/executor/bridge.ts
  src/backend/processor/metadata.ts
Labels: refactoring

#96 Better range positions for reports
  src/editor/diagnostics.ts
Labels: enhancement

#93 Hide codelens and bug step decorations when document is dirty
  src/editor/codelens.ts
  src/editor/diagnostics.ts
Labels: enhancement, bugfix

#57 Refactor executor to pass shell arguments as array
  README.md
  package.json
  src/backend/executor/bridge.ts
  src/backend/executor/process.ts
  src/editor/executor.ts
  src/editor/initialize.ts
  src/utils/config.ts
  yarn.lock
Labels: refactoring, bugfix

#97 Change value of version process type to analyzer-version
  src/backend/executor/process.ts
Labels: bugfix

#98 Expand user in the CodeChecker binary path
  src/backend/executor/process.ts
Labels: bugfix
